version: '3.5'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Password1!
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test_mysql
    volumes:
      #      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
volumes:
  db_data:
